GITHUB_ACCESS_TOKEN: 37682201bfd54a3076bea5fc887d8239080e2cc5
SCHEDULER_RATE: '30 minutes'
MYSQL_ENDPOINT: db-oss-cloud.catfkcltn5ww.eu-west-2.rds.amazonaws.com
MYSQL_PORT: 3306
MYSQL_DATABASE: oss-cloud
MYSQL_USER: admin
MYSQL_PASSWORD: Bah4alaewoup8ziesa0u
