service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, local}
  environment: 
    MYSQL_ENDPOINT: ${ssm:MYSQL_ENDPOINT}
    MYSQL_PORT: ${ssm:MYSQL_PORT}
    MYSQL_DATABASE: ${ssm:MYSQL_DATABASE}
    MYSQL_USER: ${ssm:MYSQL_USER}
    MYSQL_PASSWORD: ${ssm:MYSQL_PASSWORD}
    GITHUB_APP_ID: ${ssm:GITHUB_APP_ID}
    GITHUB_APP_PRIVATE_KEY: ${ssm:GITHUB_APP_PRIVATE_KEY}
    GITHUB_INSTALL_USER: ${ssm:GITHUB_INSTALL_USER} # username of a user that installed the app
    SCHEDULER_RATE: ${file(./config/${self:provider.stage}.yml):SCHEDULER_RATE}

plugins:
  - serverless-offline-scheduler
  - serverless-offline-dotenv
  - serverless-offline

functions:
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post
          cors: true

  getContributors:
    handler: handler.getContributors
    events:
      - http:
          path: contributors
          method: get
          cors: true

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
          cors: true
  
  updateContributionStatus:
    handler: handler.updateContributionStatus
    events:
      - http:
          path: contributionStatus
          method: post
          cors: true

  contributorVisibleContributions:
    handler: handler.getVisibleUserContributions
    events:
      - http:
          path: contributorVisible
          method: post
          cors: true
  
  updateNextContributor:
    handler: handler.updateNextContributor
    events:
      - http:
          path: updateNext
          method: get
          cors: true
      # - schedule:
      #     rate: rate(${self:provider.environment.SCHEDULER_RATE})
      
