service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, local}
  environment: ${file(./config/${self:provider.stage}.yml)}

plugins:
  - serverless-offline-scheduler
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post
          cors: true

  getContributors:
    handler: handler.getContributors
    events:
      - http:
          path: contributors
          method: get
          cors: true

  updatePullRequests:
    handler: handler.updatePullRequests
    events: # http event for testing, will probably change later
      - http:
          path: updatePullRequests
          method: get
          cors: true
      - schedule:
          rate: rate(${self:provider.environment.SCHEDULER_RATE})

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
          cors: true
  
  updateContributionStatus:
    handler: handler.updateContributionStatus
    events:
      - http:
          path: contributionStatus
          method: post
          cors: true

  contributorVisibleContributions:
    handler: handler.getVisibleUserContributions
    events:
      - http:
          path: contributorVisible
          method: post
          cors: true
      
