service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-2
  stage: ${opt:stage, local}
  environment: 
    GITHUB_ACCESS_TOKEN: ${ssm:GITHUB_ACCESS_TOKEN}
    MYSQL_ENDPOINT: ${ssm:MYSQL_ENDPOINT}
    MYSQL_PORT: ${ssm:MYSQL_PORT}
    MYSQL_DATABASE: ${ssm:MYSQL_DATABASE}
    MYSQL_USER: ${ssm:MYSQL_USER}
    MYSQL_PASSWORD: ${ssm:MYSQL_PASSWORD}
    SCHEDULER_RATE: ${file(./config/${self:provider.stage}.yml):SCHEDULER_RATE}

plugins:
  - serverless-offline-scheduler
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-dotenv-plugin

functions:
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post
          cors: true

  getContributors:
    handler: handler.getContributors
    events:
      - http:
          path: contributors
          method: get
          cors: true

  updatePullRequests:
    handler: handler.updatePullRequests
    events: # http event for testing, will probably change later
      - http:
          path: updatePullRequests
          method: get
          cors: true
      - schedule:
          rate: rate(${self:provider.environment.SCHEDULER_RATE})

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
          cors: true
  
  updateContributionStatus:
    handler: handler.updateContributionStatus
    events:
      - http:
          path: contributionStatus
          method: post
          cors: true

  contributorVisibleContributions:
    handler: handler.getVisibleUserContributions
    events:
      - http:
          path: contributorVisible
          method: post
          cors: true
  
  updateNextContributor:
    handler: handler.updateNextContributor
    events:
      - http:
          path: updateNext
          method: get
          cors: true
      
