service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x
  region: eu-west-1
  stage: ${opt:stage, 'local'}
  environment:
    MYSQL_ENDPOINT: ${ssm:/oss-cloud/${self:provider.stage}/mysql-endpoint~true}
    MYSQL_PORT: ${ssm:/oss-cloud/${self:provider.stage}/mysql-port~true}
    MYSQL_DATABASE: ${ssm:/oss-cloud/${self:provider.stage}/mysql-database~true}
    MYSQL_USER: ${ssm:/oss-cloud/${self:provider.stage}/mysql-user~true}
    MYSQL_PASSWORD: ${ssm:/oss-cloud/${self:provider.stage}/mysql-password~true}
    GITHUB_APP_ID: ${ssm:/oss-cloud/${self:provider.stage}/github-app-id~true}
    GITHUB_APP_PRIVATE_KEY: ${ssm:/oss-cloud/${self:provider.stage}/github-app-private-key~true}
    GITHUB_APP_INSTALLATION_ID: ${ssm:/oss-cloud/${self:provider.stage}/github-app-installation-id~true}
    SCHEDULER_RATE: ${file(./config/${self:provider.stage}.yml):SCHEDULER_RATE}
    AUTH_REGION: ${ssm:/oss-cloud/${self:provider.stage}/auth-region~true}
    AUTH_AWS_ACCOUNT_ID: ${ssm:/oss-cloud/${self:provider.stage}/auth-aws-account-id~true}
    AUTH_USER_POOL_ID: ${ssm:/oss-cloud/${self:provider.stage}/auth-user-pool-id~true}

plugins:
  - serverless-offline-scheduler
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-vpc-plugin

custom:
  vpcConfig:
    cidrBlock: '172.16.0.0/16'
    createNatGateway: true
    createDbSubnet: true
    createParameters: true
    #    createNetworkAcl: true
    zones:
      - eu-west-1a
      - eu-west-1b
      - eu-west-1c
    subnetGroups:
      - rds
    exportOutputs: true

functions:
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post
          cors: true

  getUser:
    handler: handler.getUser

  getContributors:
    handler: handler.getContributors
    events:
      - http:
          path: contributors
          method: get
          cors: true

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.environment.AUTH_REGION}:${self:provider.environment.AUTH_AWS_ACCOUNT_ID}:userpool/${self:provider.environment.AUTH_USER_POOL_ID}

  contributorVisibleContributions:
    handler: handler.getVisibleUserContributions
    events:
      - http:
          path: contributorVisible
          method: get
          cors: true

  updateNextContributor:
    handler: handler.updateNextContributor
    events:
      - schedule:
          rate: rate(${self:provider.environment.SCHEDULER_RATE})

  updateContributionStatus:
    handler: handler.updateContributionStatus
    events:
      - http:
          path: contributionStatus
          method: post
          cors: true
          authorizer:
            arn: arn:aws:cognito-idp:${self:provider.environment.AUTH_REGION}:${self:provider.environment.AUTH_AWS_ACCOUNT_ID}:userpool/${self:provider.environment.AUTH_USER_POOL_ID}

resources:
  Resources:
    ServerlessStorageSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: 'Inbound rules for DB'
        VpcId: !Ref VPC
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: '3306'
            ToPort: '3306'
            SourceSecurityGroupId: !GetAtt AppSecurityGroup.GroupId
    PublicOutboundRule1:
      Type: AWS::EC2::SecurityGroupEgress
      Properties:
        GroupId: !GetAtt AppSecurityGroup.GroupId
        DestinationSecurityGroupId: !Ref ServerlessStorageSecurityGroup
        IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
    PublicNACL:
      Type: AWS::EC2::NetworkAcl
      Properties:
        Tags:
          - Key: 'purspose'
            Value: 'public'
        VpcId: !Ref VPC
    InboundHTTPSNACL:
      Type: 'AWS::EC2::NetworkAclEntry'
      Properties:
        NetworkAclId: !Ref PublicNACL
        RuleNumber: '100'
        Protocol: '6'
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: '0.0.0.0/0'
        PortRange:
          From: '443'
          To: '443'
    OutboundNACL:
      Type: 'AWS::EC2::NetworkAclEntry'
      Properties:
        NetworkAclId: !Ref PublicNACL
        RuleNumber: '100'
        Protocol: '-1'
        RuleAction: 'allow'
        Egress: 'true'
        CidrBlock: '0.0.0.0/0'
        PortRange:
          From: '-1'
          To: '-1'
    ConnectorPublic1:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PublicNACL
        SubnetId: !Select [1, '${ssm:/SLS/oss-cloud-backend-prod/PublicSubnets~split}']
    ConnectorPublic2:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PublicNACL
        SubnetId: !Select [ 2, '${ssm:/SLS/oss-cloud-backend-prod/PublicSubnets~split}' ]
    ConnectorPublic3:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PublicNACL
        SubnetId: !Select [ 0, '${ssm:/SLS/oss-cloud-backend-prod/PublicSubnets~split}' ]
    PrivateNACL:
      Type: AWS::EC2::NetworkAcl
      Properties:
        Tags:
          - Key: 'purspose'
            Value: 'private'
        VpcId: !Ref VPC
    InboundNACL1:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref PrivateNACL
        RuleNumber: '100'
        Protocol: '6'
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: '172.16.0.0/21'
        PortRange:
          From: '3306'
          To: '3306'
    InboundNACL2:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref PrivateNACL
        RuleNumber: '101'
        Protocol: '6'
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: '172.16.16.0/21'
        PortRange:
          From: '3306'
          To: '3306'
    InboundNACL3:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref PrivateNACL
        RuleNumber: '102'
        Protocol: '6'
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: '172.16.32.0/21'
        PortRange:
          From: '3306'
          To: '3306'
    InboundNACL4:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref PrivateNACL
        RuleNumber: '103'
        Protocol: '6'
        RuleAction: "allow"
        Egress: "false"
        CidrBlock: '0.0.0.0/0'
        PortRange:
          From: '1024'
          To: '65535'
    OutboundPrivateNACL:
      Type: AWS::EC2::NetworkAclEntry
      Properties:
        NetworkAclId: !Ref PrivateNACL
        RuleNumber: '100'
        Protocol: '-1'
        RuleAction: 'allow'
        Egress: 'true'
        CidrBlock: '0.0.0.0/0'
        PortRange:
          From: '-1'
          To: '-1'
    ConnectorPrivate1:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 1, '${ssm:/SLS/oss-cloud-backend-prod/DBSubnets~split}' ]
    ConnectorPrivate2:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 2, '${ssm:/SLS/oss-cloud-backend-prod/DBSubnets~split}' ]
    ConnectorPrivate3:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 0, '${ssm:/SLS/oss-cloud-backend-prod/DBSubnets~split}' ]
    ConnectorPrivate4:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 1, '${ssm:/SLS/oss-cloud-backend-prod/AppSubnets~split}' ]
    ConnectorPrivate5:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 2, '${ssm:/SLS/oss-cloud-backend-prod/AppSubnets~split}' ]
    ConnectorPrivate6:
      Type: AWS::EC2::SubnetNetworkAclAssociation
      Properties:
        NetworkAclId: !Ref PrivateNACL
        SubnetId: !Select [ 0, '${ssm:/SLS/oss-cloud-backend-prod/AppSubnets~split}' ]



