service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-dotenv-plugin          # used to store github access token locally to keep it secret
  - serverless-dynamodb-local
  - serverless-offline

resources:
  Resources:
    contributors:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: contributors
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: false
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post

  getContributorPulls:
    handler: handler.updatePullRequests
    events: # http event for testing, will probably change later
      # TODO - add scheduling
      - http:
          path: updatePullRequests
          method: get

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
      
