service: oss-cloud-backend
app: myapp
org: aleksaleks123

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
