service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-offline-scheduler
  - serverless-dotenv-plugin # used to store github access token locally to keep it secret
  - serverless-offline

functions:
  addContributor:
    handler: handler.addContributor
    events:
      - http:
          path: addContributor
          method: post

  getAllContributors:
    handler: handler.getAllContributors
    events:
      - http:
          path: contributors
          method: get

  updatePullRequests:
    handler: handler.updatePullRequests
    events: # http event for testing, will probably change later
      # TODO - add scheduling
      - http:
          path: updatePullRequests
          method: get
      - schedule:
          rate: rate(${env:SCHEDULER_RATE})

  getContributions:
    handler: handler.getContributions
    events:
      - http:
          path: contributions
          method: get
      
