service: oss-cloud-backend

provider:
  name: aws
  runtime: nodejs10.x

plugins:
  - serverless-dotenv-plugin # used to store github access token locally to keep it secret
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  getContributorPulls:
    handler: handler.getPulls
    events: # http event for testing, will probably change later
            # TODO - add scheduling
      - http:
          path: contributorPulls
          method: post
      